/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author B. Anggun Chintamy
 */
public class DataMahasiswa extends Menu {
    String nama,nim,fakultas,prodi,jeniskelamin,alamat,kalimat;

    /**
     * Creates new form DataMahasiswa
     */
    public DataMahasiswa() {
        initComponents();
        jComboBox_Fakultas.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            setProdi();
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_JenisKelamin = new javax.swing.ButtonGroup();
        jPanel_DataMahasiswa = new javax.swing.JPanel();
        jLabel_Nama = new javax.swing.JLabel();
        jLabel_Nim = new javax.swing.JLabel();
        jLabel_Alamat = new javax.swing.JLabel();
        jLabel_Prodi = new javax.swing.JLabel();
        jLabel_Fakultas = new javax.swing.JLabel();
        jTextField_Nama = new javax.swing.JTextField();
        jTextField_Nim = new javax.swing.JTextField();
        jTextField_Alamat = new javax.swing.JTextField();
        jComboBox_Fakultas = new javax.swing.JComboBox<>();
        jLabel_JenisKelamin = new javax.swing.JLabel();
        jRadioButton_Pria = new javax.swing.JRadioButton();
        jRadioButton_Wanita = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_Prodi = new javax.swing.JList<>();
        jPanel_TampilanData = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Tampilan = new javax.swing.JTextArea();
        jButton_Tampilkan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_DataMahasiswa.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Mahasiswa"));

        jLabel_Nama.setText("Nama");

        jLabel_Nim.setText("Nim");

        jLabel_Alamat.setText("Alamat");

        jLabel_Prodi.setText("Prodi");

        jLabel_Fakultas.setText("Fakultas");

        jTextField_Nama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_NamaFocusLost(evt);
            }
        });

        jTextField_Nim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_NimFocusLost(evt);
            }
        });

        jComboBox_Fakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Fakultas", "Ilmu Komputer", "Teknik", "Kesehatan" }));

        jLabel_JenisKelamin.setText("Jenis Kelamin");

        buttonGroup_JenisKelamin.add(jRadioButton_Pria);
        jRadioButton_Pria.setText("Laki - laki");

        buttonGroup_JenisKelamin.add(jRadioButton_Wanita);
        jRadioButton_Wanita.setText("Perempuan");

        jScrollPane2.setViewportView(jList_Prodi);

        javax.swing.GroupLayout jPanel_DataMahasiswaLayout = new javax.swing.GroupLayout(jPanel_DataMahasiswa);
        jPanel_DataMahasiswa.setLayout(jPanel_DataMahasiswaLayout);
        jPanel_DataMahasiswaLayout.setHorizontalGroup(
            jPanel_DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DataMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DataMahasiswaLayout.createSequentialGroup()
                        .addGroup(jPanel_DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Nama)
                            .addComponent(jLabel_Nim)
                            .addComponent(jLabel_Alamat)
                            .addComponent(jLabel_JenisKelamin))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel_DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_Nama, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                .addComponent(jTextField_Nim)
                                .addComponent(jTextField_Alamat))
                            .addGroup(jPanel_DataMahasiswaLayout.createSequentialGroup()
                                .addComponent(jRadioButton_Pria)
                                .addGap(36, 36, 36)
                                .addComponent(jRadioButton_Wanita))))
                    .addGroup(jPanel_DataMahasiswaLayout.createSequentialGroup()
                        .addGroup(jPanel_DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Fakultas)
                            .addComponent(jLabel_Prodi))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel_DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_Fakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel_DataMahasiswaLayout.setVerticalGroup(
            jPanel_DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DataMahasiswaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel_DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nama)
                    .addComponent(jTextField_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nim)
                    .addComponent(jTextField_Nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Alamat)
                    .addComponent(jTextField_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_JenisKelamin)
                    .addComponent(jRadioButton_Pria)
                    .addComponent(jRadioButton_Wanita))
                .addGap(18, 18, 18)
                .addGroup(jPanel_DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Fakultas)
                    .addComponent(jComboBox_Fakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DataMahasiswaLayout.createSequentialGroup()
                        .addComponent(jLabel_Prodi)
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        jPanel_TampilanData.setBorder(javax.swing.BorderFactory.createTitledBorder("Tampilan Data"));

        jTextArea_Tampilan.setColumns(20);
        jTextArea_Tampilan.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Tampilan);

        javax.swing.GroupLayout jPanel_TampilanDataLayout = new javax.swing.GroupLayout(jPanel_TampilanData);
        jPanel_TampilanData.setLayout(jPanel_TampilanDataLayout);
        jPanel_TampilanDataLayout.setHorizontalGroup(
            jPanel_TampilanDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TampilanDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel_TampilanDataLayout.setVerticalGroup(
            jPanel_TampilanDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TampilanDataLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton_Tampilkan.setText("Tampilkan");
        jButton_Tampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TampilkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_TampilanData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_DataMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Tampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_DataMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Tampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_TampilanData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_TampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TampilkanActionPerformed
      nama = jTextField_Nama.getText();
      nim = jTextField_Nim.getText();
      alamat = jTextField_Alamat.getText();
      
      if(jRadioButton_Pria.isSelected()){
          jeniskelamin = jRadioButton_Pria.getText();
      }
      else if(jRadioButton_Wanita.isSelected()){
          jeniskelamin = jRadioButton_Wanita.getText();
      }
      
      fakultas = jComboBox_Fakultas.getSelectedItem().toString();
      
      if (jList_Prodi.getSelectedValue() != null) {
        prodi = jList_Prodi.getSelectedValue().toString();
      } 
      else {
        prodi = "Tidak ada prodi yang dipilih";
      }
      
        if (prodi != null) {
          kalimat = "Data Mahasiswa\nNama: " + nama +
                  "\nNIM: " + nim +
                  "\nAlamat: " + alamat +
                  "\nJenis kelamin: " + jeniskelamin +
                  "\nFakultas: " + fakultas +
                  "\nProdi: " + prodi;
          jTextArea_Tampilan.setText(kalimat);
        } 
        
        else {
          jTextArea_Tampilan.setText("Silakan pilih prodi");
        }
    }//GEN-LAST:event_jButton_TampilkanActionPerformed

    private void jTextField_NamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NamaFocusLost
        // TODO add your handling code here:
        checkNama();
    }//GEN-LAST:event_jTextField_NamaFocusLost

    private void jTextField_NimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NimFocusLost
        // TODO add your handling code here:
        checkNim();
    }//GEN-LAST:event_jTextField_NimFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataMahasiswa().setVisible(true);
            }
        });
    }
    
    private void checkNama(){
    boolean checkNama;
    nama = jTextField_Nama.getText();
    
    checkNama = nama.matches("[a-zA-Z\\s]+");
    
        if(!checkNama){
        jTextArea_Tampilan.setText("Nama Hanya Boleh Terdiri dari Huruf Saja");
        }
    }
    private void checkNim(){
    boolean checkNim;
    nim = jTextField_Nim.getText();
    String errorNim = "NIM Hanya Boleh Terdiri dari Angka Saja";
    
    checkNim = nim.matches("^[0-9]{10}$");
    
        if (checkNim == false){
        jTextArea_Tampilan.setText(errorNim);
        }
    }
    
    private void setProdi() {
    String fakultasSelected = jComboBox_Fakultas.getSelectedItem().toString();

    if (fakultasSelected.equalsIgnoreCase("Teknik")) {
        jList_Prodi.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Teknis Sipil", "Arsitektur"};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
    } else if (fakultasSelected.equalsIgnoreCase("Ilmu Komputer")) {
        jList_Prodi.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Informatika", "Sistem Informasi"};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
    } else if (fakultasSelected.equalsIgnoreCase("Kesehatan")) {
        jList_Prodi.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Kedokteran", "Keperawatan"};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
    } else {
        // Jika fakultas tidak dipilih atau tidak sesuai, kosongkan daftar prodi
        jList_Prodi.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_JenisKelamin;
    private javax.swing.JButton jButton_Tampilkan;
    private javax.swing.JComboBox<String> jComboBox_Fakultas;
    private javax.swing.JLabel jLabel_Alamat;
    private javax.swing.JLabel jLabel_Fakultas;
    private javax.swing.JLabel jLabel_JenisKelamin;
    private javax.swing.JLabel jLabel_Nama;
    private javax.swing.JLabel jLabel_Nim;
    private javax.swing.JLabel jLabel_Prodi;
    private javax.swing.JList<String> jList_Prodi;
    private javax.swing.JPanel jPanel_DataMahasiswa;
    private javax.swing.JPanel jPanel_TampilanData;
    private javax.swing.JRadioButton jRadioButton_Pria;
    private javax.swing.JRadioButton jRadioButton_Wanita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_Tampilan;
    private javax.swing.JTextField jTextField_Alamat;
    private javax.swing.JTextField jTextField_Nama;
    private javax.swing.JTextField jTextField_Nim;
    // End of variables declaration//GEN-END:variables
}
