/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author B. Anggun Chintamy
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar_Menu = new javax.swing.JMenuBar();
        jMenu_User = new javax.swing.JMenu();
        jMenuItem_Logout = new javax.swing.JMenuItem();
        jMenuItem_Keluar = new javax.swing.JMenuItem();
        jMenu_Data = new javax.swing.JMenu();
        jMenuItem_IsiDataMahasiswa = new javax.swing.JMenuItem();
        jMenuItem_TabelDataMahasiswa = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu_User.setText("User");
        jMenu_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_UserActionPerformed(evt);
            }
        });

        jMenuItem_Logout.setText("Logout");
        jMenuItem_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_LogoutActionPerformed(evt);
            }
        });
        jMenu_User.add(jMenuItem_Logout);

        jMenuItem_Keluar.setText("Exit System");
        jMenuItem_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_KeluarActionPerformed(evt);
            }
        });
        jMenu_User.add(jMenuItem_Keluar);

        jMenuBar_Menu.add(jMenu_User);

        jMenu_Data.setText("Data");
        jMenu_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_DataActionPerformed(evt);
            }
        });

        jMenuItem_IsiDataMahasiswa.setText("Isi Data Mahasiswa");
        jMenuItem_IsiDataMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_IsiDataMahasiswaActionPerformed(evt);
            }
        });
        jMenu_Data.add(jMenuItem_IsiDataMahasiswa);

        jMenuItem_TabelDataMahasiswa.setText("Tabel Data Mahasiswa");
        jMenuItem_TabelDataMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TabelDataMahasiswaActionPerformed(evt);
            }
        });
        jMenu_Data.add(jMenuItem_TabelDataMahasiswa);

        jMenuBar_Menu.add(jMenu_Data);

        setJMenuBar(jMenuBar_Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_UserActionPerformed

    private void jMenu_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_DataActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu_DataActionPerformed

    private void jMenuItem_IsiDataMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_IsiDataMahasiswaActionPerformed
        // TODO add your handling code here:
        dispose();
        
        DataMahasiswa formDataMahasiswa = new DataMahasiswa();
        formDataMahasiswa.setVisible(true);
    }//GEN-LAST:event_jMenuItem_IsiDataMahasiswaActionPerformed

    private void jMenuItem_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_KeluarActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_jMenuItem_KeluarActionPerformed

    private void jMenuItem_TabelDataMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TabelDataMahasiswaActionPerformed
        // TODO add your handling code here:
        dispose();
        
        TableData formTableData = new TableData();
        formTableData.setVisible(true);
    }//GEN-LAST:event_jMenuItem_TabelDataMahasiswaActionPerformed

    private void jMenuItem_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_LogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        
        Login formLogin = new Login();
        formLogin.setVisible(true);
    }//GEN-LAST:event_jMenuItem_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar_Menu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem_IsiDataMahasiswa;
    private javax.swing.JMenuItem jMenuItem_Keluar;
    private javax.swing.JMenuItem jMenuItem_Logout;
    private javax.swing.JMenuItem jMenuItem_TabelDataMahasiswa;
    private javax.swing.JMenu jMenu_Data;
    private javax.swing.JMenu jMenu_User;
    // End of variables declaration//GEN-END:variables
}
